version: '3'
services:
  tfschema:
    build:
      context: .
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION:-latest}
    volumes:
      - ".:/work"
    environment:
      CGO_ENABLED: 0 # disable cgo for go test
      # Use the same filesystem to avoid a checksum mismatch error
      # or a file busy error caused by asynchronous IO.
      TF_PLUGIN_CACHE_DIR: "/tmp/plugin-cache"
